import base64

import requests
from mcp.server import MCPServer

GITHUB_API = "https://api.github.com"

server = MCPServer(
    name="github-mcp-server",
    instructions=(
        "GitHub par repository banane aur code files push/commit karne ke "
        "tools deta hai. Har tool call ke sath ek valid GitHub Personal "
        "Access Token (kam se kam 'repo' scope wala) dena zaroori hai."
    ),
)


def _headers(github_token: str) -> dict:
    return {
        "Authorization": f"Bearer {github_token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }


@server.tool()
def get_authenticated_user(github_token: str) -> dict:
    """
    Diye gaye Personal Access Token se GitHub par login hone wale user ka
    info nikalta hai. Isko token verify karne ke liye pehle call karo.
    """
    resp = requests.get(f"{GITHUB_API}/user", headers=_headers(github_token), timeout=15)
    if resp.status_code != 200:
        return {"ok": False, "status": resp.status_code, "error": resp.text}
    data = resp.json()
    return {"ok": True, "login": data.get("login"), "name": data.get("name")}


@server.tool()
def create_repository(
    github_token: str,
    repo_name: str,
    private: bool = False,
    description: str = "Generated by Software House CrewAI",
) -> dict:
    """
    GitHub par naya repository banata hai token wale account ke andar.
    Agar isi naam ka repo pehle se maujood hai to error nahi degi —
    `already_exists: true` return karegi taake caller seedha push_files
    par chala jaye.
    """
    resp = requests.post(
        f"{GITHUB_API}/user/repos",
        headers=_headers(github_token),
        json={
            "name": repo_name,
            "private": private,
            "description": description,
            "auto_init": True,  # README ke sath banega, is liye default branch turant available hoga
        },
        timeout=15,
    )
    if resp.status_code == 201:
        data = resp.json()
        return {
            "ok": True,
            "already_exists": False,
            "full_name": data["full_name"],
            "html_url": data["html_url"],
            "default_branch": data.get("default_branch", "main"),
        }
    if resp.status_code == 422:
        return {"ok": True, "already_exists": True, "message": "Is naam ka repo pehle se maujood hai."}
    return {"ok": False, "status": resp.status_code, "error": resp.text}


@server.tool()
def push_files(
    github_token: str,
    owner: str,
    repo_name: str,
    files: dict[str, str],
    commit_message: str = "Add CrewAI generated code",
    branch: str = "main",
) -> dict:
    """
    `files` (path -> raw text content) ke har entry ko repo mein
    create ya update (agar file already maujood hai) kar deta hai,
    GitHub Contents API (PUT /repos/{owner}/{repo}/contents/{path}) se.
    """
    pushed: list[str] = []
    failed: list[dict] = []

    for path, content in files.items():
        url = f"{GITHUB_API}/repos/{owner}/{repo_name}/contents/{path}"

        # Agar file already exist karti hai to uska current sha chahiye hoga
        # (GitHub update ke liye sha maangta hai, warna 409/422 dega)
        existing = requests.get(url, headers=_headers(github_token), params={"ref": branch}, timeout=15)
        sha = existing.json().get("sha") if existing.status_code == 200 else None

        payload = {
            "message": commit_message,
            "content": base64.b64encode(content.encode("utf-8")).decode("utf-8"),
            "branch": branch,
        }
        if sha:
            payload["sha"] = sha

        put_resp = requests.put(url, headers=_headers(github_token), json=payload, timeout=20)
        if put_resp.status_code in (200, 201):
            pushed.append(path)
        else:
            failed.append({"path": path, "status": put_resp.status_code, "error": put_resp.text})

    return {
        "ok": len(failed) == 0,
        "pushed": pushed,
        "failed": failed,
        "repo_url": f"https://github.com/{owner}/{repo_name}",
    }


if __name__ == "__main__":
    # Standalone: `python -m mcp_server.github_server`
    # stdio transport par chalega — MCP Inspector se yahan connect karke
    # tools ko manually test kiya ja sakta hai.
    server.run()
